### ISSUE TITLE
Sidonia color scheme not accessible

### ISSUE THREAD

**Issue by powelleric** [AlessandroYorba/Arcadia#4]
Hello, I recently saw the sidonia colorscheme and I like it a lot but when I try to click any links for it github takes me to a 404 page.  

Have you decided to make the repository private?

**Comment by AlessandroYorba** [comment]
@powelleric Hi Eric, sorry.  Truth be told, I wasn't happy with the results. I kept fussing with changes and color adjustments over and over that I felt it reached a point where it lost it's identity <== Not sure that makes sense. Anyways, I plan to revisit it. Funny enough, Arcadia went through the same process.
